---
version: '3'
services:

  ## Postgres database
  postgres-db:
    image: postgres:15.2-alpine
    container_name: postgres_example-2
#    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example_password
      - POSTGRES_DB=example_two
    ports:
      - '5432:5432'
  #    volumes:
  #      - db:/var/lib/postgresql/data